#! /bin/sh
# Minimal STartup

cmde() {
	type "$1" &> /dev/null
}

DISTRO="unknown"
PKGM="unknown"
PKGC="unknown"
DCOL="$(tput setaf 11)"

cmde "pacman-key"
if [ $? -eq 0 ]; then
	DISTRO="arch"
	PKGM="alpm"
	PKGC="$(pacman -Qq --color never | wc -l)"
	DCOL="$(tput setaf 12)"
fi

cmde "apt-cache"
if [ $? -eq 0 ]; then
	DISTRO="debian"
	PKGM="dpkg"
	PKGC="$(dpkg -l | grep -c '^?i' | wc -l)"
	DCOL="$(tput setaf 13)"
fi

cmde "yum"
if [ $? -eq 0 ]; then
	DISTRO="redhat"
	PKGM="rpm"
	PKGC="$(rpm -qa | wc -l)"
	DCOL="$(tput setaf 9)"
fi

cmde "zypper"
if [ $? -eq 0 ]; then
	DISTRO="suse"
	PKGM="rpm"
	PKGC="$(rpm -qa | wc -l)"
	DCOL="$(tput setaf 10)"
fi

cmde "xbps-query"
if [ $? -eq 0 ]; then
	DISTRO="void"
	PKGM="xbps"
	PKGC="$(xbps-query -l | wc -l)"
	DCOL="$(tput setaf 10)"
fi

cmde "emerge"
if [ $? -eq 0 ]; then
	DISTRO="gentoo"
	PKGM="emerge"
	PKGC="$(cd /var/db/pkg/ && ls -d */* | wc -l)"
	DCOL="$(tput setaf 13)"
fi

cmde "port"
if [ $? -eq 0 ]; then
	DISTRO="macos"
	PKGM="macports"
	PKGC="$(port echo installed | wc -l | sed 's/^[ \t]*//')"
	DCOL="$(tput setaf 11)"
fi

cmde "brew"
if [ $? -eq 0 ]; then
	DISTRO="macos"
	PKGM="homebrew"
	PKGC="$(brew list | wc -l)"
	DCOL="$(tput setaf 11)"
fi

EDC="\e[0m"
WI="$(tput setaf 15)"
STC1="$(tput setaf 14)"
STC2="$(tput setaf 11)"
STC3="$(tput setaf 13)"
STC4="$(tput setaf 10)"
STC5="$(tput setaf 12)"
STC6="$(tput setaf 4)"
STC7="$(tput setaf 10)"
main() {
	cat <<- EOF
	this is $STC1$(uname -n)$WI
	distro: $DCOL$DISTRO$WI
	packages: $DCOL$PKGC$WI ($DCOL$PKGM$WI)
	kernel ver: $STC4$(uname -r | sed s/-/\ /g | awk '{print $1 }')$WI
	logged in as: $STC2$(whoami)$WI
	working directory: $STC3$PWD$WI
	EOF
	echo "shell: $STC7$(echo $SHELL | sed s/\\//\ /g | awk '{print $(NF)}')"
	printf "\e[m\n"
}

main
